(defpackage #:%3b-swf
  (:use #:cl)
  (:nicknames #:%swf)
  (:export
   #:rect #:xmin #:xmax #:ymin #:ymax
   #:rgba #:rgb #:r #:g #:b #:a
   #:file-attributes-tag
   #:use-direct-blit
   #:use-gpu
   #:has-metadata
   #:actionscript-3
   #:use-network
   #:script-limits-tag
   #:max-recursion-depth
   #:script-timeout-seconds
   #:matrix-part-fixed
   #:value1
   #:value2
   #:matrix-part-translate
   #:matrix
   #:scale
   #:rotate-skew
   #:translate
   #:swf-tag
   #:swf-show-frame-tag
   #:read-swf-part
   #:%swf-part-size
   #:write-swf-part
   #:character-id
   #:define-shape-tag
   #:place-object-tag
   #:remove-object-tag
   #:define-bits-tag
   #:define-button
   #:jpeg-tables
   #:set-background-color-tag
   #:define-font-tag
   #:background-color
   #:define-text-tag
   #:do-action
   #:actions
   #:define-font-info-tag
   #:define-sound-tag
   #:start-sound-tag
   #:define-button-sound
   #:sound-stream-head
   #:sound-stream-block
   #:define-bits-lossless-tag
   #:define-bits-jpeg-2-tag
   #:image-data
   #:define-shape-2-tag
   #:shapes
   #:bounds
   #:shape-with-style
   #:define-button-cxform-tag
   #:protect-tag
   #:place-object-2-tag
   #:move-flag
   #:depth
   #:matrix
   #:color-transform
   #:po2-ratio
   #:name
   #:clip-depth
   #:clip-actions
   #:remove-object-2-tag
   #:define-shape-3-tag
   #:define-text-2-tag
   #:matrix
   #:define-button-2-tag
   #:define-bits-jpeg-3-tag
   #:define-bits-lossless-2-tag
   #:define-edit-text-tag
   #:define-sprite-tag
   #:frame-label-tag
   #:sound-stream-head-2-tag
   #:define-morph-shape
   #:start-bounds
   #:end-bounds
   #:offset
   #:morph-fill-styles
   #:morph-line-styles
   #:start-edges
   #:end-edges
   #:define-font-2-tag
   #:export-assetsx-tag
   #:enable-debugger-tag
   #:do-init-action-tag
   #:define-video-stream-tag
   #:video-frame-tag
   #:define-font-info-2-tag
   #:enable-debugger-2
   #:place-object-3-tag
   #:has-image
   #:class-name
   #:matrix
   #:po3-ratio
   #:surface-filter-list
   #:blend-mode
   #:bitmap-cache
   #:import-assets-2-tag
   #:define-font-align-zones-tag
   #:csm-text-settings-tag
   #:define-font-3-tag
   #:symbol-class-tag
   #:num-symbols
   #:symbol-class-symbols
   #:metadata-tag
   #:metadata
   #:do-abc-tag
   #:flags
   #:data
   #:define-shape-4-tag
   #:edge-bounds
   #:uses-fill-winding-rule
   #:uses-non-scaling-strokes
   #:uses-scaling-strokes
   #:define-morph-shape-2-tag
   #:start-edge-bounds
   #:end-edge-bounds
   #:define-scene-and-frame-label-data-tag
   #:scene-count
   #:scenes
   #:frame-label-count
   #:frames
   #:define-font-name-tag
   #:swf-end-tag
   #:named-anchor-flag
   #:frame-count
   #:control-tags
   #:cxform-with-alpha
   #:cxform
   #:add
   #:mult
   #:blur-filter
   #:glow-filter
   #:blur-x
   #:blur-y
   #:passes
   #:inner-glow
   #:strength
   #:knockout
   #:inner-glow
   #:glow-color
   #:filter-list
   #:filters))